[package]
name = "xgboost"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

